model = "gpt-5.4"
[projects."/Users/andriiprokhorenko"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/WebstormProjects/715-unitedRentals-reportGeneration"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/Desktop"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/WebstormProjects/vx-api-siffron"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/.config/nvim/lua/plugins"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/StudioProjects/gitpractice"]
trust_level = "trusted"

[projects."/Applications"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/test"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/.config/nvim/lua/config"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/Library/Android/sdk"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/StudioProjects/austal-mobile/austal-mobile"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/StudioProjects/siffron-mobile"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/.dotfiles"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/Desktop/vlad/cc_final"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/Downloads"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/Desktop/vlad"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/Desktop/drills"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/drills"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/drills/bash-drills"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/drills/bash-drills/day1round2"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/drills/bash-drills/day2"]
trust_level = "trusted"

[projects."/Users/andriiprokhorenko/WebstormProjects/chirpstack-decoders"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
