set -g mouse off
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
unbind C-b
set -g prefix M-j
bind M-j send-prefix

bind r source-file ~/.tmux.conf \; display-message "reloaded"

bind e send-keys C-g

bind h if-shell -F '#{||:#{==:#{pane_current_command},nvim},#{==:#{pane_current_command},vim}}' 'send-keys M-j h' 'select-pane -L'
bind j if-shell -F '#{||:#{==:#{pane_current_command},nvim},#{==:#{pane_current_command},vim}}' 'send-keys M-j j' 'select-pane -D'
bind k if-shell -F '#{||:#{==:#{pane_current_command},nvim},#{==:#{pane_current_command},vim}}' 'send-keys M-j k' 'select-pane -U'
bind l if-shell -F '#{||:#{==:#{pane_current_command},nvim},#{==:#{pane_current_command},vim}}' 'send-keys M-j l' 'select-pane -R'

bind m split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

setw -g mode-keys vi
bind [ copy-mode

set -g status-left-length 40
set -g status-style 'fg=#a89984,bg=#282828'
set -g status-right-style 'fg=#928374,bg=#282828'
set -g status-right "%d/%m/%Y %H:%M"

set -g pane-border-lines heavy
set -g pane-border-style 'fg=#504945'
set -g pane-active-border-style 'fg=#83a598'
set -g window-style 'fg=#928374,bg=#282828'
set -g window-active-style 'fg=#ebdbb2,bg=#282828'
set -g pane-border-status top
set -g pane-border-format ' #{?pane_active,#[fg=#282828 bg=#83a598] ACTIVE #[default],#[fg=#928374] pane #[default]} #{pane_index}: #{pane_current_command} '

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
